-- creating database
create database if not exists PORTS_DB;
use PORTS_DB;


--creating schema
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS TASK_STREAM;


-- creating file format to load csv files
CREATE OR REPLACE FILE FORMAT BRONZE.CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '')
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_BLANK_LINES = TRUE;



-- creating storage integration
-- CREATE OR REPLACE STORAGE INTEGRATION AZURE_PORTS_INT
-- TYPE = EXTERNAL_STAGE
-- STORAGE_PROVIDER = 'AZURE'
-- ENABLED = TRUE
-- AZURE_TENANT_ID = '732352a1-88ad-4073-bcd9-899701c44885'
-- STORAGE_ALLOWED_LOCATIONS = ('azure://snowblob123.blob.core.windows.net/port/');



-- creating external stage
-- CREATE OR REPLACE STAGE BRONZE.ALL_FILES_STAGE
-- URL = 'azure://snowblob123.blob.core.windows.net/port/'
-- STORAGE_INTEGRATION = AZURE_PORTS_INT
-- FILE_FORMAT = BRONZE.CSV_FORMAT;

CREATE OR REPLACE STAGE BRONZE.SNOW_FILES
FILE_FORMAT = BRONZE.CSV_FORMAT;

list @BRONZE.SNOW_FILES;

CREATE OR REPLACE WAREHOUSE PORTS_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;
